### ISSUE TITLE
Add more context to readme.md

### ISSUE THREAD

**Issue by igalloway** [NXPHoverGames/NXP_AIM_INDIA_2024#1]
@mayankmahajan-nxp  @sumitbatra-nxp  Reminder that you should probably add more context to the readme for this project.
For a first time viewer, It is not clear what boards, and what software environment that this is for.

Also a small introductory paragraph about the overall system or the overall project would be helpful. 
You can also provide a couple of links to the NXP gitbook and products. so people that may not be immediately part of AIM can find out more details about the hardware pieces as well.

**Comment by mayankmahajan-nxp** [comment]
Noted @igalloway. I will make the necessary changes.

**Comment by mayankmahajan-nxp** [comment]
Hi @igalloway, I have made changes according to your comments. Kindly review the latest commit and let me know if it's ok.

**Comment by mayankmahajan-nxp** [comment]
Hi @igalloway, I am closing this issue. Kindly let me know if any further changes are required.
